### ISSUE TITLE
[4] UI-Mockup & revision

### ISSUE THREAD

**Issue by richjoregonstate** [tigerman9854/ModelViewer#17]
- Design a basic UI mockup for sprint 1 issues

**Comment by richjoregonstate** [comment]
Initial mockup.

We still need to sort out how we want the shader editor to look like / work. Whether that be opening a separate window, opening their (the user's) editor, or some other method. Also, the question of animations may be something we look at for later sprints? 
![image](https://user-images.githubusercontent.com/25143405/95779129-57009280-0c7e-11eb-940a-3b86963dbf6b.png)

**Comment by tigerman9854** [comment]
I like the mockup!

I think the shader editor would work best as a separate window.  There's also the option of having docking windows... but probably overly complicated for this project.

Linking to other programs would be cool if you know how to do that, for example opening Notepad++ as an editor.
