### ISSUE TITLE
[5] Fix non-working mouse tests

### ISSUE THREAD

**Issue by richjoregonstate** [tigerman9854/ModelViewer#30]
checkMousePressAndRelease() and panWithMouse() in test.cpp are non fucntional due to the mouse events not triggering.

![image](https://user-images.githubusercontent.com/25143405/97036146-3c4ed900-151c-11eb-82ad-e0a6997ce8a0.png)

**Comment by tigerman9854** [comment]
I think this is complete now

**Comment by richjoregonstate** [comment]
Closed w/ #38
