### ISSUE TITLE
[2] Change sceneMatrix to rotation matrix & translation matrix...

### ISSUE THREAD

**Issue by richjoregonstate** [tigerman9854/ModelViewer#32]
Keep a separate matrix for translation, rotation, scale, and view (matrix.perspective). Then, in the render() function, compute the overall transformation by multiplying these together each frame.

I think this is the right order of matrices.... Order does matter so try changing them around if it doesn't work.
FinalMat = view * scale * trans * rot

**Comment by tigerman9854** [comment]
I added to the above comment^

**Comment by richjoregonstate** [comment]
Swapped over to the scale * view * translation * rotation. Got a small issue where zooming in seems to be moving the object behind the camera.

![issue](https://user-images.githubusercontent.com/25143405/97046278-fe59b100-152b-11eb-9789-28dd3d45500c.gif)

**Comment by tigerman9854** [comment]
Is this going to be a separate pull request?  If so, I can approve the current one.

**Comment by richjoregonstate** [comment]
Yes, this will be a part of sprint 2.

**Comment by zunyueseattle** [comment]
it seems work for translation and rotation

**Comment by tigerman9854** [comment]
It works from the user's perspective.  To make our code more robust (and easier to add future features), Jonathan will be modifying the algorithm.
