### ISSUE TITLE
[4] Export to different file types

### ISSUE THREAD

**Issue by richjoregonstate** [tigerman9854/ModelViewer#39]

**Comment by tigerman9854** [comment]
http://assimp.sourceforge.net/lib_html/class_assimp_1_1_exporter.html

**Comment by tigerman9854** [comment]
Hi Chenyun, I had some ideas to make this story easier.  When we load a 3D model in `ModelLoader.cpp`, we store it as an `aiScene*`.  That is the format that is needed for export in this function: http://assimp.sourceforge.net/lib_html/class_assimp_1_1_exporter.html#ab8edf249172567a78ca302278a415e35 .  In order for this `aiScene` pointer to stay valid, we cannot allow the `Assimp::Importer` object to be destroyed.  I'd recommend making `LoadModel()` a static function, and `Assimp::Importer` a static member of the ModelLoader class.  Then you can use Qt to let the user select a filepath.

Hope this helps :)
