### ISSUE TITLE
[2] Mockup axes and dimensions display

### ISSUE THREAD

**Issue by richjoregonstate** [tigerman9854/ModelViewer#40]

**Comment by tigerman9854** [comment]
Option 1, simple axes with letters on them:
![image](https://user-images.githubusercontent.com/13424385/99433507-749aca80-28c2-11eb-9661-8b84dac91091.png)

Option 2, colored axes:
![image](https://user-images.githubusercontent.com/13424385/99433525-782e5180-28c2-11eb-8812-f83d4242702d.png)

**Comment by tigerman9854** [comment]
I will add gridlines as a floor:
![image](https://user-images.githubusercontent.com/13424385/99433655-a3b13c00-28c2-11eb-9c6f-9e694270501c.png)

**Comment by tigerman9854** [comment]
![image](https://user-images.githubusercontent.com/13424385/99453243-85a30600-28d9-11eb-8c4e-c3a7ddb175b8.png)

**Comment by tigerman9854** [comment]
The axes on the object need to have a disable button.
