### ISSUE TITLE
[10] Polish menus

### ISSUE THREAD

**Issue by tigerman9854** [tigerman9854/ModelViewer#80]
DONE:
- [x] Make sure that closing the main window closes the settings menu
- [x] Reorder the menus to make more sense.  See user comments from the last sprint
- [x] Toggle grid / fps / stats view-menu option
- [x] Keybinds rebind in a 'normal' way :)
- [x] List of previously opened files on startup
- [x] MSAA slider

**Comment by richjoregonstate** [comment]
https://doc.qt.io/qt-5/stylesheet-reference.html
