### ISSUE TITLE
[10] Set up development environment

### ISSUE THREAD

**Issue by tigerman9854** [tigerman9854/ModelViewer#9]
Follow instructions in readme to:
 - Install visual studio 2019
 - Install Qt and configure in VS 2019
 - Clone the repository and build

Acceptance Criteria(AC): Must be able to run the project.

Ask Kyle for help.

**Comment by richjoregonstate** [comment]
![image](https://user-images.githubusercontent.com/25143405/95284766-db34bf00-0813-11eb-8b1f-1a4a99686926.png)
I'm in :)

**Comment by tigerman9854** [comment]
@richjoregonstate Were you able to get OpenGL to render a triangle?  The screenshot looks blank...  It should just work.

**Comment by richjoregonstate** [comment]
![af](https://user-images.githubusercontent.com/25143405/95289506-b5adb280-081f-11eb-8eef-adc4d54fb3d2.gif)

Yes, I was just a pull or two behind :)

Also, look at that compression...
